    server:
      port: 8082


    logging:
    file:
        name: /opt/tomcat/webapps/app.log
    level:
        org:
            springframework: ERROR

        edu:
            th_owl:
                modules_management: INFO

    pattern:
        dateformat: dd-MM-yyyy HH:mm:ss a

